language: ruby
cache: bundler

rvm:
  - 2.3.0

before_install:
  - gem install bundler -v 1.11.2

before_script:
  - bin/setup

deploy:
  provider: rubygems
  api_key:
    secure: "PjJHSumQrG07it7nXgxh4YR9y+jOXQeBsCvq3cEkyg7XpLFCtWoJjEJY8Tyxv4yFXd6PEs1Y/0m6XBdm05wlogiSTYTra9s1agc/Xpq2kxghr41978S2cOEjuJaid0n41BsXuZsOK2fnwyrgwgWIeiwSlW89DvnjvjIqzS7lEqock0ArVkDkZR3lFfGDKjGfrfQas3NwVQV1GTmO6HSaHx9F/lSrcLb2zBqUdHmpWGTjq8Pnkwyy1FG0qWPgh6J+qapaNqk1J5a8/Wcs05K9H6O5IbJHL5wa1vH0MJLfbo8Ti1iLNBjBKVCv3mhkZMJ9uKJtsAp4uZpyqEaDPtUNGPxan31ByiLd+QH5eTp721DCWyt+KfAkI2O27zjN8GZohLmxL5xFPaYi1N3gf1E2e4rAy74+5ZneMA7to3DRAMgH6OgLri33wOTLUqbLvlHKDV/r/Nak7lYoIv8A33sNxBADmIXoqt6PkyCQ/a8ZBSutsSyXVCrAzjpl4vhOiLjpPV3DekGfIW9JfXLWHMtJw//F88k5F/gWtB+sCWKjOSiM10zPVDYIgC8FaYZneCZpV1OAVzOIXWKxr5wDbkHHUg1NB5lnLXC4U+svcC4yuZIz0RdRZQm9MxXS8ZiIu7Zx3l8aI+I9p5RmIpeOpwWT78w9dWCZH/9ekjqLpqGHfHQ="
  gem: active_record_stats
  on:
    tags: true
    repo: enova/active_record_stats

env:
  global:
    secure: oJ83X6WVeW7owbJ2Lj6wfGepDDCPtYohgBW9ShDZcc4Lb8FcvQ3+iz3GoS1i9L1Z995wnku894KemN2t0Ntr347e0vlpibH5ffCQIKhSMmjyGGSIIfNS9YaCSPV/fvwTPgxBby2sszUdzLQA4nR7tMGg0WQIeXCTUOUvU8EuIevY51oWLwKlbBcj1ZKBt6qZCMEfXuleuOzouKVcS6PHF2NuSckDSZ/7kA99jQL5AOORoL851G9eMbtiSbrUIgI+GqF7jAwPmC1XneR5lCq4Tq9iEoEJp/Vi56l7Ur2/WeLX01gl/bCqCk7Ty1ISYAynyT5Uiu3kXeI/bDRDiclOSbUa7YOAI6thWC6RyjC4wJ0wu8n58ONjkaiX/qaixx8gfL7nkEUGrn4qDhtY2rizTS7zde7+H0Q6MpASB9WhAnXvFSEROR7aQf4VeMdaznvc1Bio8fyoNi5ca/a+EcsCBnFg+qVQ1I5o4NR7Qaz39BZjsqQqwGRME1ND/UWQVta9eWKDIg65sbgRZmD6TI25lHxQaAIiVyFANRDdYYlO6WWEfFZg4auJJpiczkJgudbbckQ9m0xoz33ZFxgjJN3E4wK3ojMJ20YwQyVa4nQ5KeoQP6NT793IQ9ANjmR8rKcyFWDKM52oTv4x2AgW0vQo2lnTCC+n8vY9p/GcflEZbc8=
